import type { ProjectLocation } from "./globalProjectDashboard.types";

export const projectLocations: ProjectLocation[] = [
    {
        id: "mumbai",
        name: "Mumbai",
        country: "India",
        latitude: 19.076,
        longitude: 72.8777,
        ongoing: 12,
        completed: 5,
        projects: [
            { name: "Mumbai Metro Development", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Port Modernization", client: "Marine Infrastructure", status: "Ongoing" },
            { name: "Solar Energy Project", client: "Renewable Energy", status: "Ongoing" },
            { name: "Airport Expansion", client: "Aviation Division", status: "Ongoing" },
            { name: "Smart City Development", client: "Urban Development", status: "Completed" },
        ],
    },
    {
        id: "dubai",
        name: "Dubai",
        country: "United Arab Emirates",
        latitude: 25.2048,
        longitude: 55.2708,
        ongoing: 8,
        completed: 4,
        projects: [
            { name: "Dubai Infrastructure Project", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Smart City Initiative", client: "Technology Division", status: "Ongoing" },
            { name: "Commercial Development", client: "Real Estate Division", status: "Ongoing" },
            { name: "Solar Power Plant", client: "Energy Division", status: "Completed" },
        ],
    },
    {
        id: "london",
        name: "London",
        country: "United Kingdom",
        latitude: 51.5074,
        longitude: -0.1278,
        ongoing: 5,
        completed: 7,
        projects: [
            { name: "London Transport Upgrade", client: "Transport Division", status: "Ongoing" },
            { name: "Office Development", client: "Commercial Division", status: "Ongoing" },
            { name: "River Infrastructure", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Energy Efficiency Program", client: "Energy Division", status: "Completed" },
        ],
    },
    {
        id: "new-york",
        name: "New York",
        country: "United States",
        latitude: 40.7128,
        longitude: -74.006,
        ongoing: 24,
        completed: 10,
        projects: [
            { name: "Manhattan Infrastructure", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Commercial Tower", client: "Real Estate Division", status: "Ongoing" },
            { name: "Transit Modernization", client: "Transport Division", status: "Ongoing" },
            { name: "Digital Infrastructure", client: "Technology Division", status: "Ongoing" },
            { name: "Energy Grid Upgrade", client: "Energy Division", status: "Completed" },
        ],
    },
    {
        id: "singapore",
        name: "Singapore",
        country: "Singapore",
        latitude: 1.3521,
        longitude: 103.8198,
        ongoing: 18,
        completed: 6,
        projects: [
            { name: "Singapore Smart City", client: "Technology Division", status: "Ongoing" },
            { name: "Port Expansion", client: "Marine Division", status: "Ongoing" },
            { name: "Green Building Program", client: "Sustainability Division", status: "Ongoing" },
            { name: "Digital Infrastructure", client: "Technology Division", status: "Completed" },
        ],
    },
    {
        id: "sydney",
        name: "Sydney",
        country: "Australia",
        latitude: -33.8688,
        longitude: 151.2093,
        ongoing: 7,
        completed: 3,
        projects: [
            { name: "Sydney Harbour Development", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Urban Development", client: "Urban Planning", status: "Ongoing" },
            { name: "Renewable Energy Program", client: "Energy Division", status: "Completed" },
        ],
    },
    {
        id: "johannesburg",
        name: "Johannesburg",
        country: "South Africa",
        latitude: -26.2041,
        longitude: 28.0473,
        ongoing: 31,
        completed: 9,
        projects: [
            { name: "African Infrastructure Program", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Mining Infrastructure", client: "Mining Division", status: "Ongoing" },
            { name: "Energy Development", client: "Energy Division", status: "Ongoing" },
            { name: "Transport Network", client: "Transport Division", status: "Ongoing" },
            { name: "Urban Development", client: "Urban Planning", status: "Completed" },
        ],
    },
    {
        id: "sao-paulo",
        name: "São Paulo",
        country: "Brazil",
        latitude: -23.5505,
        longitude: -46.6333,
        ongoing: 14,
        completed: 8,
        projects: [
            { name: "São Paulo Metro", client: "Transport Division", status: "Ongoing" },
            { name: "Urban Infrastructure", client: "Infrastructure Division", status: "Ongoing" },
            { name: "Green Energy Project", client: "Energy Division", status: "Ongoing" },
            { name: "Smart Mobility", client: "Technology Division", status: "Completed" },
        ],
    },
    {
        id: "tokyo",
        name: "Tokyo",
        country: "Japan",
        latitude: 35.6762,
        longitude: 139.6503,
        ongoing: 42,
        completed: 15,
        projects: [
            { name: "Tokyo Smart Infrastructure", client: "Technology Division", status: "Ongoing" },
            { name: "Rail Network Expansion", client: "Transport Division", status: "Ongoing" },
            { name: "Urban Development Program", client: "Urban Planning", status: "Ongoing" },
            { name: "Renewable Energy Program", client: "Energy Division", status: "Ongoing" },
            { name: "Digital City Program", client: "Technology Division", status: "Completed" },
        ],
    },
];
